config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { in: 0..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: :post_id
  has_many :comments

  after_create :update_post_counter

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # The index method is responsible for fetching and displaying a list of posts belonging to a specific user
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  # The show method displays only further details on a single post and user
  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  # The new method lets Rails know that you will create a new object
  def new
    @post = Post.new
  end

  # It starts by finding the User object based on the user_id parameter
  # Then, it creates a new Post object associated with that user

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_posts_path(@user)
        else
          render :new, locals: { post: @post }
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @current_user, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>
    <div class="post_form">
      <h3>Add New Post</h3>
      <div>
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'post_title' %>
        <%if form&.object&.errors%>
          <% form.object.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
          <% end %>
        <% end %>
      </div>
      <br>
      <div>
        <%= form.label :text %><br>
        <%= form.text_area :text, class: 'post_text' %>
        <%if form&.object&.errors%>
          <% form.object.errors.full_messages_for(:text).each do |message| %>
          <div><%= message %></div>
          <% end %>
        <% end %>
      </div>
      <br>
      <%= form.submit "Create Post", class: "post_button" %>
    </div>
  <% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'post_index' %>

<%= render "shared/userblock", user: @user %>

<div class="all-posts">
  <% @user.posts.includes(:comments).each_with_index do |post, index| %>
    <%= link_to user_post_path(user_id: @user.id, id: post.id), class: "see-post" do %>
      <div class="post-box">
        <span>Post #<%= index + 1 %></span>
        <p><%= post.text %></p>
        <div class="post-info">
          <span>Comments: <%= post.comments_counter %></span>
          <span>Likes: <%= post.likes_counter %></span>
        </div>
      </div>
    <% end %>

    <div class="comment-box">
      <% if post.comments.empty? %>
        <%= "No comments yet!" %>
      <% else %>
        <% post.comments.each do |comment| %>
          <div>
            <span><%= "#{comment.author.name}: " %></span>
            <span><%= comment.text %></span>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to new_user_post_path(params[:user_id]), class: "posts-btn" do %>
  <%= "Add new Post" %>
<% end %>

app/views/posts/new.html.erb
<%= render "form", post:@post%>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'post_show' %>

<div class="post-box">
    <div class="top">
        <div class="post-details">
            <span>Post #<%= Post.where(author_id: @user.id).find_index(@post).to_i + 1 %> by <%= @user.name %></span>
        </div>
        <div class="post-stats">
            <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
        </div>
    </div>
    
    <div class="main">
        <p><%= @post.text %></p>
    </div>
    <div class="bottom">
        <%= render 'shared/like', like: @like %>
    </div>
</div>

<div class="comments-box">
    <% if Comment.where(post_id: @post).empty? %>
                <%= "No comments yet!"%>
            <%else%>
                <% Comment.where(post_id: @post).each do |comment| %>
                    <div>
                    <span><%= "#{comment.author.name}: "%></span>
                    <span><%= comment.text %></span>
                    </div>
            <% end %>
    <% end %>
</div>
<div class="add-comment">
    <h3>Add a Comment</h3>
    <%= render 'shared/comment', post: @post %>
</div>